[wokwi]
version = 1
firmware = "firmware/RPI_PICO-20251209-v1.27.0.uf2"
elf = ""
rfc2217ServerPort = 4000

# repl_test.py is mounted as main.py so the Pico runs it on boot
[[fs]]
path = "src/repl_test.py"
name = "main.py"

[[fs]]
path = "src/event_bus.py"

[[fs]]
path = "src/midi_message.py"

[[fs]]
path = "src/midi_input.py"

[[fs]]
path = "src/midi_output.py"

[[fs]]
path = "src/midi_clock_tracker.py"

[[fs]]
path = "src/midi_router.py"

[[fs]]
path = "src/uart_writer.py"

[[fs]]
path = "src/tempo_to_cc.py"

[[fs]]
path = "src/config.py"

[[fs]]
path = "src/system_builder.py"

[[fs]]
path = "src/config.json"
